<?xml version="1.0" encoding="windows-1250" standalone="yes"?>

<!DOCTYPE ceginfo[

<!ELEMENT ceginfo (ceg+)>
<!ATTLIST ceg nev CDATA #REQUIRED>
<!ELEMENT ceg (alapitas, tulaj+, alkalmazottak?, fizetes, elerhetosegek, tevekenyseg+, nyitvatartas)>
<!ELEMENT alapitas EMPTY>
<!ATTLIST alapitas ev CDATA #REQUIRED>
<!ELEMENT tulaj (nev, telefonszam?, email?)>
<!ELEMENT nev (#PCDATA)>
<!ELEMENT telefonszam (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT alkalmazottak (alkalmazott+)>
<!ELEMENT alkalmazott (nev, beosztas, fizetes, telefonszam)>
<!ATTLIST alkalmazott szemelyi ID #REQUIRED>
<!ATTLIST fizetes mod (keszpenz|bank|paypal) "keszpenz">
<!ELEMENT beosztas (#PCDATA)>
<!ELEMENT fizetes (#PCDATA)>
<!ELEMENT elerhetosegek (cim, telefonszam+, weboldal?, email?)>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT weboldal (#PCDATA)>
<!ELEMENT tevekenyseg (profil, termekek)>
<!ELEMENT profil (#PCDATA)>
<!ELEMENT termekek (termek)>
<!ELEMENT termek (#PCDATA)>
<!ELEMENT nyitvatartas (hetkoznap?, hetvege?)>
<!ELEMENT hetkoznap (#PCDATA)>
<!ELEMENT hetvege (#PCDATA)>
]>



<ceginfo>
	<ceg nev="Extreme Digital">
		<alapitas ev="2001"/>
		<tulaj>
			<nev>Kiss Gedeon</nev>
			<telefonszam>06204876325</telefonszam>
			<email>valami@gmail.com</email>
		</tulaj>
		<tulaj>
			<nev>Gergo Aron</nev>
			<telefonszam>06704201205</telefonszam>
			<email>g.aron@gmail.com</email>
		</tulaj>
		<alkalmazottak>
			<alkalmazott szemelyi="654234IA">
				<nev>Kiss Eva</nev>
				<beosztas>elado</beosztas>
				<fizetes>180000</fizetes>
				<telefonszam>06702541896</telefonszam>
			</alkalmazott>
			<alkalmazott szemelyi="765787RA">
				<nev>Benedek Elek</nev>
				<beosztas>raktaros</beosztas>
				<fizetes>150000</fizetes>
				<telefonszam>06204572345</telefonszam>
			</alkalmazott>
		</alkalmazottak>
		<fizetes mod="bank"/>
		<elerhetosegek>
			<cim>Debrecen, Hajnal utca 76, 4034</cim>
			<telefonszam>0652487154</telefonszam>
			<weboldal>extremedigital.hu</weboldal>
			<email>info@extremedigital.hu</email>
		</elerhetosegek>
		<tevekenyseg>
			<profil>Muszaki Webaruhaz</profil>
			<termekek>
				<termek>Televiziok</termek>
				<termek>Szamitogepek</termek>
				<termek>Mosogepek</termek>
			</termekek>
		</tevekenyseg>
		<nyitvatartas>
			<hetkoznap>7-18</hetkoznap>
			<hetvege>7-12</hetvege>
		</nyitvatartas>
	</ceg>
	
	<ceg nev="Alensa.hu">
		<alapitas ev="2005"/>
		<tulaj>
			<nev>Nagy Zoltan</nev>
			<telefonszam>06704129876</telefonszam>
			<email>n.zoltan@alensa.hu</email>
		</tulaj>
		<alkalmazottak>
			<alkalmazott szemelyi="346324IA">
				<nev>Rozsa Ilona</nev>
				<beosztas>elado</beosztas>
				<fizetes>140000</fizetes>
				<telefonszam>06302345345</telefonszam>
			</alkalmazott>
			<alkalmazott szemelyi="875456RA">
				<nev>Ferenc Tamas</nev>
				<beosztas>beszallito</beosztas>
				<fizetes>200000</fizetes>
				<telefonszam>06202343867</telefonszam>
			</alkalmazott>
			<alkalmazott szemelyi="345678RA">
				<nev>Gal Tamas</nev>
				<beosztas>futar</beosztas>
				<fizetes>240000</fizetes>
				<telefonszam>06302121145</telefonszam>
			</alkalmazott>
		</alkalmazottak>
		<fizetes mod="bank"/>
		<elerhetosegek>
			<cim>Budapest, RÃ³zsa utca 101, 1064</cim>
			<telefonszam>0614088300</telefonszam>
			<weboldal>www.alensa.hu</weboldal>
			<email>info@alensa.hu</email>
		</elerhetosegek>
		<tevekenyseg>
			<profil>Kontaktlencse Webaruhaz</profil>
			<termekek>
				<termek>Kontaktlencsek</termek>
				<termek>Apolo folyadekok</termek>
				<termek>Kiegeszitok</termek>
			</termekek>
		</tevekenyseg>
		<nyitvatartas>
			<hetkoznap>8-16</hetkoznap>
			<hetvege>8-13</hetvege>
		</nyitvatartas>
	</ceg>
</ceginfo>